### ISSUE TITLE
kopere

### ISSUE THREAD

**Issue by anibalrlopez** [EduardoKrausME/moodle-local-kopere_dashboard#102]
I installed the latest version in moodle 4.1.1 and I get this message:

**Error**
Excepción - Call to undefined function get_string_kopere()

![image](https://github.com/user-attachments/assets/de567637-4538-458d-ad1a-f722d2c200d9)

Please I need your help to solve this!

**Comment by eduardokraus** [comment]
https://moodle.org/plugins/local_kopere_dashboard/2.8.2/34318

**Comment by dymitar** [comment]
This is actually not solved in 2.8.7.
There is a problem with the 3 files in event folder.
The problem is somehow related to the autoload and namespaces.
As I'm not very familiar with Moodle autoload, I solved this by changing the code in the 3 files not to use get_string_copere.
But there should be a proper solution for this.

`    public static function get_name() {
        //return get_string_kopere("userimport_import_course_enrol_name");
        return get_string("userimport_import_course_enrol_name", "local_kopere_dashboard");
    }
`
