### ISSUE TITLE
Task \local_kopere_dashboard\task\db_course_access failed

### ISSUE THREAD

**Issue by gigadep** [EduardoKrausME/moodle-local-kopere_dashboard#96]
Hi,
I use Moodle 4.4.2 with PHP 8.2.
I have a problem with the cron \local_kopere_dashboard\task\db_course_access
This message appears :

"scheduled task: Cron to store user logins in temporary table (local_kopere_dashboard\task\db_course_access)
... started 04:15:18. Current memory use 59.8 Mo.
... used 2 dbqueries
... used 1.0247011184692 seconds
Scheduled task failed: Cron to store user logins in temporary table (local_kopere_dashboard\task\db_course_access),Erreur de lecture de la base de données (You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '::text, userid::text, contextinstanceid::text) AS a, COUNT(*) AS contagem,
  ...' at line 1

                SELECT CONCAT(courseid::text, userid::text, contextinstanceid::text) AS a, COUNT(*) AS contagem,
                       courseid, userid, contextinstanceid, timecreated
                  FROM mdl_logstore_standard_log
                 WHERE action = 'viewed'
                   AND timecreated BETWEEN (CURRENT_DATE - INTERVAL '30 DAY') AND CURRENT_DATE
              GROUP BY courseid, userid, contextinstanceid, timecreated
              ORDER BY timecreated DESC
[array (
)])
Debug info:
You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '::text, userid::text, contextinstanceid::text) AS a, COUNT(*) AS contagem,
  ...' at line 1

                SELECT CONCAT(courseid::text, userid::text, contextinstanceid::text) AS a, COUNT(*) AS contagem,
                       courseid, userid, contextinstanceid, timecreated
                  FROM mdl_logstore_standard_log
                 WHERE action = 'viewed'
                   AND timecreated BETWEEN (CURRENT_DATE - INTERVAL '30 DAY') AND CURRENT_DATE
              GROUP BY courseid, userid, contextinstanceid, timecreated
              ORDER BY timecreated DESC
[array (
)]
Backtrace:
* line 293 of /lib/dml/moodle_read_slave_trait.php: call to moodle_database->query_end()
* line 1398 of /lib/dml/mysqli_native_moodle_database.php: call to mysqli_native_moodle_database->query_end()
* line 60 of /local/kopere_dashboard/classes/task/db_course_access.php: call to mysqli_native_moodle_database->get_records_sql()
* line 410 of /lib/classes/cron.php: call to local_kopere_dashboard\task\db_course_access->execute()
* line 208 of /lib/classes/cron.php: call to core\cron::run_inner_scheduled_task()
* line 125 of /lib/classes/cron.php: call to core\cron::run_scheduled_tasks()
* line 186 of /admin/cli/cron.php: call to core\cron::run_main_process()"

Thank you

Jean-Gabriel

**Comment by jamc60** [comment]
Hi.
I get exactly same issue with moodle 4.4.3, php 8.1.29 and mariadb 10.11.9.

Execute scheduled task: Cron to store user logins in temporary table (local_kopere_dashboard\task\db_course_access)
... started 12:02:04. Current memory use 35.4 MB.
Debugging increased temporarily due to faildelay of 960
... used 2 dbqueries
... used 0.0032899379730225 seconds
Scheduled task failed: Cron to store user logins in temporary table (local_kopere_dashboard\task\db_course_access),Error al leer de la base de datos (You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '::text, userid::text, contextinstanceid::text) AS a, COUNT(*) AS contagem,
  ...' at line 1

                SELECT CONCAT(courseid::text, userid::text, contextinstanceid::text) AS a, COUNT(*) AS contagem,
                       courseid, userid, contextinstanceid, timecreated
                  FROM mdl_logstore_standard_log
                 WHERE action = 'viewed'
                   AND timecreated BETWEEN (CURRENT_DATE - INTERVAL '30 DAY') AND CURRENT_DATE
              GROUP BY courseid, userid, contextinstanceid, timecreated
              ORDER BY timecreated DESC
[array (
)])
Debug info:
You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '::text, userid::text, contextinstanceid::text) AS a, COUNT(*) AS contagem,
  ...' at line 1

                SELECT CONCAT(courseid::text, userid::text, contextinstanceid::text) AS a, COUNT(*) AS contagem,
                       courseid, userid, contextinstanceid, timecreated
                  FROM mdl_logstore_standard_log
                 WHERE action = 'viewed'
                   AND timecreated BETWEEN (CURRENT_DATE - INTERVAL '30 DAY') AND CURRENT_DATE
              GROUP BY courseid, userid, contextinstanceid, timecreated
              ORDER BY timecreated DESC
[array (
)]
Backtrace:
* line 293 of /lib/dml/moodle_read_slave_trait.php: call to moodle_database->query_end()
* line 1398 of /lib/dml/mysqli_native_moodle_database.php: call to mysqli_native_moodle_database->query_end()
* line 60 of /local/kopere_dashboard/classes/task/db_course_access.php: call to mysqli_native_moodle_database->get_records_sql()
* line 410 of /lib/classes/cron.php: call to local_kopere_dashboard\task\db_course_access->execute()
* line 208 of /lib/classes/cron.php: call to core\cron::run_inner_scheduled_task()
* line 125 of /lib/classes/cron.php: call to core\cron::run_scheduled_tasks()
* line 186 of /admin/cli/cron.php: call to core\cron::run_main_process()

**Comment by eduardokraus** [comment]
https://github.com/EduardoKrausME/moodle-local-kopere_dashboard/commit/7e7220a2dcd17dc03a628622566c02b70f59d17d
